---
- name: apt update cache
  listen: apt_update_cache
  ansible.builtin.apt:
    update_cache: true
    cache_valid_time: 3600

- name: restart docker
  listen: docker_service
  ansible.builtin.service:
    name: docker
    state: restarted
