---
- name: Ensure required packages are installed
  ansible.builtin.apt:
    name:
      - ca-certificates
      - curl
    state: present
    update_cache: true
  tags: 
    - install_docker
    - os_ubuntu

- name: Create directory for Docker GPG key
  ansible.builtin.file:
    path: /etc/apt/keyrings
    state: directory
    mode: "0755"
  tags: 
    - install_docker

- name: Download Docker GPG key
  ansible.builtin.get_url:
    url: https://download.docker.com/linux/ubuntu/gpg
    dest: /etc/apt/keyrings/docker.asc
    mode: "0644"
    force: true
  tags: 
    - install_docker

- name: Add Docker apt repository
  ansible.builtin.apt_repository:
    repo: "deb [signed-by=/etc/apt/keyrings/docker.asc] https://download.docker.com/linux/ubuntu {{ ansible_distribution_release }} stable"
    filename: docker
    state: present
  register: docker_repo
  notify: apt_update_cache
  tags: 
    - install_docker
    - os_ubuntu

# Ensure the handler runs before we try to install packages
- name: Flush handlers if repository was added/changed
  ansible.builtin.meta: flush_handlers
  when: docker_repo is changed
  tags: 
    - install_docker

- name: Install Docker Engine and related packages
  ansible.builtin.apt:
    name:
      - docker-ce
      - docker-ce-cli
      - containerd.io
      - docker-buildx-plugin
      - docker-compose-plugin
    state: present
  notify: docker_service
  tags: 
    - install_docker

- name: Ensure Docker service is enabled and started
  ansible.builtin.service:
    name: docker
    enabled: true
    state: started
  tags: 
    - configure

- name: Ensure group "docker" exists
  ansible.builtin.group:
    name: docker
    state: present
  tags: 
    - configure

- name: Ensure user/system account is tied to docker group
  ansible.builtin.user:
    name: test
    groups: docker
    append: true
  tags: 
    - configure

- name: Run hello-world to verify Docker installation
  ansible.builtin.command: docker run --rm hello-world
  register: docker_output
  failed_when: "'Hello from Docker!' not in docker_output.stdout"
  changed_when: false
  tags: 
    - validate
