---
# ================== READ ME ================== #

# ================== READ ME ================== #

- name: Set up Docker repository on Ubuntu
  hosts: 
  order: sorted
  become: true
  gather_facts: true
  roles: 
    - docker
  apply:
    tags:
      - docker