---
# ================== READ ME ================== #

# ================== READ ME ================== #

- name: Set up Docker repository on Ubuntu
  hosts: digfor-pve
  order: sorted
  become: true
  gather_facts: true
  roles: 
    - software
  tags:
    - install_docker
    - install_kubectl